<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RollForward>Major</RollForward>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <WarningsAsErrors>true</WarningsAsErrors>
    <WarningLevel>9999</WarningLevel>
    <DisableMSBuildAssemblyCopyCheck>true</DisableMSBuildAssemblyCopyCheck>

  </PropertyGroup>

  <PropertyGroup>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <!--<IncludeSymbols>false</IncludeSymbols>-->
    <!--<SymbolPackageFormat>snupkg</SymbolPackageFormat>-->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build" ExcludeAssets="runtime"/>
    <!--<PackageReference Include="Microsoft.Build" Version="17.14.8" ExcludeAssets="runtime"/>-->
    <PackageReference Include="Microsoft.Build.Locator" />
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Sbom.Api" />
    <PackageReference Include="CycloneDX.Core" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

  <PropertyGroup>
    <CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>bld</ToolCommandName>
    <AssemblyName>bld</AssemblyName>
    <!--<PackageOutputPath></PackageOutputPath>-->
    <!--<RuntimeIdentifier>win-x64</RuntimeIdentifier>-->
    <!--<PackageId></PackageId>-->
    <PackageId>Cloudsiders.bld</PackageId>
    <PackageVersion>0.1.1</PackageVersion>
    <Authors>dlosch</Authors>
    <Description>Tool to clean build output folders for msbuild</Description>
    <PackageTags>msbuild</PackageTags>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <!--<PackageLicenseFile>LICENSE</PackageLicenseFile>-->
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>
  <ItemGroup>
    <!--<None Include="LICENSE" Pack="true" PackagePath="" />-->
  </ItemGroup>

  <Target Name="Foo">
    <Warning Text="$(MSBuildExtensionsPath)" />
  </Target>
</Project>
