<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RollForward>Major</RollForward>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <WarningsAsErrors>true</WarningsAsErrors>
    <WarningLevel>9999</WarningLevel>
    <DisableMSBuildAssemblyCopyCheck>true</DisableMSBuildAssemblyCopyCheck>

  </PropertyGroup>

  <PropertyGroup>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <!--<IncludeSymbols>false</IncludeSymbols>-->
    <!--<SymbolPackageFormat>snupkg</SymbolPackageFormat>-->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build" ExcludeAssets="runtime" />
    <!--<PackageReference Include="Microsoft.Build" Version="17.14.8" ExcludeAssets="runtime"/>-->
    <PackageReference Include="Microsoft.Build.Locator" />
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
    <PackageReference Include="NuGet.Protocol" />
    <PackageReference Include="NuGet.Versioning" />
    <PackageReference Include="NuGet.Packaging" />
    <PackageReference Include="NuGet.Frameworks" />
    <PackageReference Include="ModelContextProtocol" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <PropertyGroup>
    <CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>bld</ToolCommandName>
    <AssemblyName>bld</AssemblyName>
    <!--<PackageOutputPath></PackageOutputPath>-->
    <!--<RuntimeIdentifier>win-x64</RuntimeIdentifier>-->
    <!--<PackageId></PackageId>-->
    <PackageId>Cloudsiders.bld</PackageId>
    <PackageVersion>0.1.1</PackageVersion>
    <Authors>dlosch</Authors>
    <Description>A .NET tool for managing MSBuild projects: clean build output, analyze NuGet packages, migrate target frameworks, enable Central Package Management, and discover containers.</Description>
    <PackageTags>msbuild;nuget;dotnet-tool;clean;build;cpm;tfm;containers</PackageTags>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <!--<PackageLicenseFile>LICENSE</PackageLicenseFile>-->
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/dlosch/bld</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="/"/>
  </ItemGroup>

</Project>
