// Generated by Copilot - GPT-4o
using bld.Services.NuGet;
using NuGet.Protocol.Core.Types;
using Xunit.Abstractions;

namespace NugetMetadata.Tests.Integration;

public class ManualTests {
    private readonly ITestOutputHelper Console;
    //private readonly INugetMetadataService _service;

    public ManualTests(ITestOutputHelper console) {
        Console = console;

        //var services = new ServiceCollection();
        //services.AddLogging();
        //services.AddNugetMetadata();

        //var serviceProvider = services.BuildServiceProvider();
        //_service = serviceProvider.GetRequiredService<INugetMetadataService>();
    }


    [Theory]
    [InlineData("coverlet.collector", "net9.0")]
    [InlineData("xunit", "net9.0")]
    [InlineData("NSwag.ApiDescription.Client", "net8.0")]
    [InlineData("Microsoft.Sbom.Targets", "net8.0")]
    [InlineData("Microsoft.Extensions.ApiDescription.Server", "net9.0")]
    [InlineData("Microsoft.Extensions.ApiDescription.Client", "net8.0")]
    [InlineData("MemoryPack.Generator", "net10.0")]
    public async Task NoCompatibleVersion(string packageId, string tfm) {
        Console.WriteLine($"https://api.nuget.org/v3/registration5-gz-semver2/{packageId.ToLower()}/index.json");
        var request = new PackageVersionRequest {
            PackageId = packageId,
            AllowPrerelease = false,
            CompatibleTargetFrameworks = [tfm]
        };
        var options = new NugetMetadataOptions { MaxParallelRequests = 1 /* configure */ };
        var client = NugetMetadataService.CreateHttpClient(options);
        // Act
        var result = await NugetMetadataService.GetLatestVersionWithFrameworkCheckAsync(client, options, default, request);
        // Assert
        Assert.NotNull(result);
        Assert.NotEmpty(result.TargetFrameworkVersions);
        Console.WriteLine(result.Deps());
        Console.WriteLine($"Found versions: {string.Join(", ", result.TargetFrameworkVersions.Select(kv => $"{kv.Key}:{kv.Value}"))}");

    }

    [Theory]
    [InlineData("Grpc.AspNetCore")]
    public async Task HandleMetapackageDetection(string packageId) {
        // https://api.nuget.org/v3/registration5-gz-semver2/grpc.aspnetcore/index.json
        // 

        // Arrange
        var request = new PackageVersionRequest {
            PackageId = packageId,
            AllowPrerelease = false,
            CompatibleTargetFrameworks = []
        };
        var options = new NugetMetadataOptions { MaxParallelRequests = 1 /* configure */ };
        var client = NugetMetadataService.CreateHttpClient(options);
        // Act
        var result = await NugetMetadataService.GetLatestVersionWithFrameworkCheckAsync(client, options, default, request);
        // Assert
        Assert.NotNull(result);
        Assert.NotEmpty(result.TargetFrameworkVersions);
        Console.WriteLine($"Found versions: {string.Join(", ", result.TargetFrameworkVersions.Select(kv => $"{kv.Key}:{kv.Value}"))}");
    }


    // "NSwag.ApiDescription.Client" net9.0
    [Theory()]
    //[InlineData("NugetMetadata.Configuration")] // no such package afaik
    [InlineData("Newtonsoft.Json")]
    [InlineData("Microsoft.Build.Utilities.Core")]
    [InlineData("System.Data.DataSetExtensions")]
    [InlineData("MemoryPack")]
    //[InlineData("MemoryPack.Generator")]
    public async Task RunPackageIds(string packageId) {
        // Arrange
        var request = new PackageVersionRequest {
            PackageId = packageId,
            AllowPrerelease = false,
            CompatibleTargetFrameworks = ["net8.0", "netstandard2.0"]
        };

        var options = new NugetMetadataOptions { MaxParallelRequests = 1 /* configure */ };

        var client = NugetMetadataService.CreateHttpClient(options);
        // Act
        var result = await NugetMetadataService.GetLatestVersionWithFrameworkCheckAsync(client, options, default, request);

        // Assert
        Assert.NotNull(result);
        Assert.NotEmpty(result.TargetFrameworkVersions);
        Console.WriteLine($"Found versions: {string.Join(", ", result.TargetFrameworkVersions.Select(kv => $"{kv.Key}:{kv.Value}"))}");
    }

    [Theory()]
    [InlineData("MemoryPack.Generator")]
    public async Task RunPackageIdsNoTfm(string packageId) {
        // Arrange
        var request = new PackageVersionRequest {
            PackageId = packageId,
            AllowPrerelease = false,
            IsPrivateAssets = true,
            CompatibleTargetFrameworks = Array.Empty<string>()
        };

        var options = new NugetMetadataOptions { MaxParallelRequests = 1 /* configure */ };

        var client = NugetMetadataService.CreateHttpClient(options);
        // Act
        var result = await NugetMetadataService.GetLatestVersionWithFrameworkCheckAsync(client, options, default, request);

        // Assert
        Assert.NotNull(result);
        Assert.NotEmpty(result.TargetFrameworkVersions);
        Console.WriteLine($"Found versions: {string.Join(", ", result.TargetFrameworkVersions.Select(kv => $"{kv.Key}:{kv.Value}"))}");
    }

    // "" net9.0
    [Theory()]
    //[InlineData("NSwag.ApiDescription.Client", "net9.0")]
    [InlineData("OpenTelemetry.Instrumentation.StackExchangeRedis", "net9.0")]

    public async Task RunPackageIdsSpecific(string packageId, string tfm) {
        // Arrange
        var request = new PackageVersionRequest {
            PackageId = packageId,
            AllowPrerelease = false,
            CompatibleTargetFrameworks = [tfm]
        };

        var options = new NugetMetadataOptions { MaxParallelRequests = 1 /* configure */ };

        var client = NugetMetadataService.CreateHttpClient(options);
        // Act
        var result = await NugetMetadataService.GetLatestVersionWithFrameworkCheckAsync(client, options, default, request);

        // Assert
        Assert.NotNull(result);
        Assert.NotEmpty(result.TargetFrameworkVersions);
        Console.WriteLine($"Found versions: {string.Join(", ", result.TargetFrameworkVersions.Select(kv => $"{kv.Key}:{kv.Value}"))}");
    }


    [Theory()]
    [InlineData("Microsoft.Build.Utilities.Core", false)]
    [InlineData("Microsoft.Build.Utilities.Core", true)]
    [InlineData("Microsoft.Extensions.Logging", false)]
    [InlineData("Microsoft.Extensions.Logging", true)]
    public async Task RunPackageIdsMulti(string packageId, bool allowPre) {
        // Arrange
        var request = new PackageVersionRequest {
            PackageId = packageId,
            AllowPrerelease = allowPre,
            CompatibleTargetFrameworks = ["net8.0", "net6.0", "netstandard2.0"]
            //CompatibleTargetFrameworks = ["net8.0", "net6.0", "netstandard2.0", "net472"]
        };

        var options = new NugetMetadataOptions { MaxParallelRequests = 1 /* configure */ };

        var client = NugetMetadataService.CreateHttpClient(options);
        // Act
        var result = await NugetMetadataService.GetLatestVersionWithFrameworkCheckAsync(client, options, default, request);

        // Assert
        Assert.NotNull(result);
        Assert.NotEmpty(result.TargetFrameworkVersions);
        Console.WriteLine($"Found versions: {string.Join(", ", result.TargetFrameworkVersions.Select(kv => $"{kv.Key}:{kv.Value}"))}");
    }
}

public static class Ext {
    public static string Deps(this PackageVersionResult result) {
        if (result.Dependencies?.Count == 0) {
            return "<none>";
        }

        var txt = "Deps:\r\n";
        foreach (var item in result.Dependencies.Keys.Order()) {
            var elem = result.Dependencies[item].Dependencies;
            foreach (var dep in elem) {
                txt += $"- {item}: {dep.PackageId} {dep.Range}\r\n";

            }
        }

        return txt;
    }
}