// Generated by Copilot - GPT-4o
using bld.Services.NuGet;
using Xunit.Abstractions;

namespace NugetMetadata.Tests.Integration;

public class ManualTests {
    private readonly ITestOutputHelper Console;
    //private readonly INugetMetadataService _service;

    public ManualTests(ITestOutputHelper console) {
        Console = console;

        //var services = new ServiceCollection();
        //services.AddLogging();
        //services.AddNugetMetadata();

        //var serviceProvider = services.BuildServiceProvider();
        //_service = serviceProvider.GetRequiredService<INugetMetadataService>();
    }

    // "NSwag.ApiDescription.Client" net9.0
    [Theory()]
    //[InlineData("NugetMetadata.Configuration")] // no such package afaik
    [InlineData("Newtonsoft.Json")]
    [InlineData("Microsoft.Build.Utilities.Core")]
    [InlineData("System.Data.DataSetExtensions")]
    [InlineData("MemoryPack")]
    //[InlineData("MemoryPack.Generator")]
    public async Task RunPackageIds(string packageId) {
        // Arrange
        var request = new PackageVersionRequest {
            PackageId = packageId,
            AllowPrerelease = false,
            CompatibleTargetFrameworks = ["net8.0", "netstandard2.0"]
        };

        var options = new NugetMetadataOptions { MaxParallelRequests = 1 /* configure */ };

        var client = NugetMetadataService.CreateHttpClient(options);
        // Act
        var result = await NugetMetadataService.GetLatestVersionWithFrameworkCheckAsync(client, options, default, request);

        // Assert
        Assert.NotNull(result);
        Assert.NotEmpty(result.TargetFrameworkVersions);
        Console.WriteLine($"Found versions: {string.Join(", ", result.TargetFrameworkVersions.Select(kv => $"{kv.Key}:{kv.Value}"))}");
    }

    [Theory()]
    [InlineData("MemoryPack.Generator")]
    public async Task RunPackageIdsNoTfm(string packageId) {
        // Arrange
        var request = new PackageVersionRequest {
            PackageId = packageId,
            AllowPrerelease = false,
            IsPrivateAssets = true,
            CompatibleTargetFrameworks = Array.Empty<string>()
        };

        var options = new NugetMetadataOptions { MaxParallelRequests = 1 /* configure */ };

        var client = NugetMetadataService.CreateHttpClient(options);
        // Act
        var result = await NugetMetadataService.GetLatestVersionWithFrameworkCheckAsync(client, options, default, request);

        // Assert
        Assert.NotNull(result);
        Assert.NotEmpty(result.TargetFrameworkVersions);
        Console.WriteLine($"Found versions: {string.Join(", ", result.TargetFrameworkVersions.Select(kv => $"{kv.Key}:{kv.Value}"))}");
    }

    // "" net9.0
    [Theory()]
    //[InlineData("NSwag.ApiDescription.Client", "net9.0")]
    [InlineData("OpenTelemetry.Instrumentation.StackExchangeRedis", "net9.0")]

    public async Task RunPackageIdsSpecific(string packageId, string tfm) {
        // Arrange
        var request = new PackageVersionRequest {
            PackageId = packageId,
            AllowPrerelease = false,
            CompatibleTargetFrameworks = [tfm]
        };

        var options = new NugetMetadataOptions { MaxParallelRequests = 1 /* configure */ };

        var client = NugetMetadataService.CreateHttpClient(options);
        // Act
        var result = await NugetMetadataService.GetLatestVersionWithFrameworkCheckAsync(client, options, default, request);

        // Assert
        Assert.NotNull(result);
        Assert.NotEmpty(result.TargetFrameworkVersions);
        Console.WriteLine($"Found versions: {string.Join(", ", result.TargetFrameworkVersions.Select(kv => $"{kv.Key}:{kv.Value}"))}");
    }


    [Theory()]
    [InlineData("Microsoft.Build.Utilities.Core", false)]
    [InlineData("Microsoft.Build.Utilities.Core", true)]
    [InlineData("Microsoft.Extensions.Logging", false)]
    [InlineData("Microsoft.Extensions.Logging", true)]
    public async Task RunPackageIdsMulti(string packageId, bool allowPre) {
        // Arrange
        var request = new PackageVersionRequest {
            PackageId = packageId,
            AllowPrerelease = allowPre,
            CompatibleTargetFrameworks = ["net8.0", "net6.0", "netstandard2.0"]
            //CompatibleTargetFrameworks = ["net8.0", "net6.0", "netstandard2.0", "net472"]
        };

        var options = new NugetMetadataOptions { MaxParallelRequests = 1 /* configure */ };

        var client = NugetMetadataService.CreateHttpClient(options);
        // Act
        var result = await NugetMetadataService.GetLatestVersionWithFrameworkCheckAsync(client, options, default, request);

        // Assert
        Assert.NotNull(result);
        Assert.NotEmpty(result.TargetFrameworkVersions);
        Console.WriteLine($"Found versions: {string.Join(", ", result.TargetFrameworkVersions.Select(kv => $"{kv.Key}:{kv.Value}"))}");
    }
}