// Generated by Copilot - GPT-4o
using bld.Infrastructure;
using NuGet.Frameworks;
using NuGet.Versioning;
using System.Net.Http.Json;
using System.Runtime.CompilerServices;
using System.Text.Json.Serialization;

[assembly: InternalsVisibleTo("bld.Tests")]
namespace bld.Services.NuGet;

public static class NugetMetadataService {

    public static HttpClient CreateHttpClient(NugetMetadataOptions options) {
        ArgumentNullException.ThrowIfNull(options);

        var clientHandler = new HttpClientHandler {
            AutomaticDecompression = System.Net.DecompressionMethods.All
        };

        var client = new HttpClient(clientHandler);
        client.Timeout = options.HttpTimeout;
        if (!client.DefaultRequestHeaders.Contains("User-Agent")) {
            client.DefaultRequestHeaders.Add("User-Agent", "NugetMetadata/1.0.0");
        }
        client.DefaultRequestVersion = new Version(2, 0);
        client.DefaultVersionPolicy = HttpVersionPolicy.RequestVersionOrLower;
        return client;
    }

    private static DefaultCompatibilityProvider _compatibilityProvider = new DefaultCompatibilityProvider();

    internal static async ValueTask<PackageVersionResult?> GetLatestVersionWithFrameworkCheckAsync(
        HttpClient httpClient,
        NugetMetadataOptions options,
        IConsoleOutput? logger,
        //ILogger? logger,
        PackageVersionRequest request,
        CancellationToken cancellationToken = default) {
        ArgumentNullException.ThrowIfNull(httpClient);
        ArgumentNullException.ThrowIfNull(options);
        ArgumentNullException.ThrowIfNull(request);

        if (string.IsNullOrWhiteSpace(request.PackageId))
            throw new ArgumentException("PackageId cannot be null or empty", nameof(request));

        try {
            var indexUrl = $"https://api.nuget.org/v3/registration5-gz-semver2/{request.PackageId.ToLowerInvariant()}/index.json";
            logger?.WriteDebug($"Getting registration index for package {request.PackageId} at {indexUrl}");

            var indexResponse = await httpClient.GetAsync(indexUrl, cancellationToken);

            if (!indexResponse.IsSuccessStatusCode) {
                if (indexResponse.StatusCode == System.Net.HttpStatusCode.NotFound) {
                    logger?.WriteInfo($"Package {request.PackageId} not found");
                    return null;
                }

                logger?.WriteInfo($"Failed to get registration index for {request.PackageId}. Status: {indexResponse.StatusCode}");
                return null;
            }

            var index = await indexResponse.Content.ReadFromJsonAsync<CatalogRoot2>(CatalogJsonContext.Default.CatalogRoot2, cancellationToken);

            if (index?.Items == null || !index.Items.Any()) {
                logger?.WriteDebug($"No pages found in registration index for {request.PackageId}");
                return null;
            }

            var allowPrerelease = request.AllowPrerelease;
retry:
            for (int i = index.Items.Count - 1; i >= 0; i--) {
                var pageItem = index.Items[i];

                if (pageItem.Items is null) {
                    var pageUrl = pageItem.Id;
                    logger?.WriteDebug($"Requesting page {pageUrl} for {request.PackageId}");

                    var pageResponse = await httpClient.GetAsync(pageUrl, cancellationToken);
                    if (!pageResponse.IsSuccessStatusCode) {
                        logger?.WriteInfo($"Failed to get page {pageUrl} for {request.PackageId}. Status: {pageResponse.StatusCode}");
                        continue;
                    }

                    var pageDetails2 = await pageResponse.Content.ReadFromJsonAsync<CatalogPage2>(CatalogJsonContext.Default.CatalogPage2, cancellationToken);
                    if (pageDetails2 is null || pageDetails2.Items is null || !pageDetails2.Items.Any()) {
                        logger?.WriteDebug($"No items found in page {pageUrl} for {request.PackageId}");
                        continue;
                    }

                    pageItem.Items = pageDetails2.Items;
                }

                var page = pageItem;

                if (page?.Items == null || !page.Items.Any())
                    continue;

                // Scan versions in page from bottom to top (latest first)
                for (int j = page.Items.Count - 1; j >= 0; j--) {
                    var versionItem = page.Items[j];

                    if (!versionItem.CatalogEntry.Listed)
                        continue;

                    var isPrerelease = NuGetVersion.TryParse(versionItem.CatalogEntry.Version, out var nugetVersion) && nugetVersion.IsPrerelease;
                    if (!allowPrerelease && isPrerelease)
                        continue;

                    var supportedFrameworks = new Dictionary<string, string>(request.CompatibleTargetFrameworks?.Count ?? 1);

                    if (!(request.CompatibleTargetFrameworks?.Any() ?? false)) {
                        supportedFrameworks["any"] = versionItem.CatalogEntry.Version;
                    }
                    else {
                        foreach (var reqFramework in request.CompatibleTargetFrameworks) {
                            if (versionItem.CatalogEntry.DependencyGroups is null || !versionItem.CatalogEntry.DependencyGroups.Any()) continue;

                            bool hasMatchingFramework = versionItem.CatalogEntry.DependencyGroups.Any(dg => {
                                if (string.IsNullOrWhiteSpace(dg.TargetFramework))
                                    return reqFramework.Equals("any", StringComparison.OrdinalIgnoreCase);
                                var dgFramework = NuGetFramework.Parse(dg.TargetFramework);
                                var reqNuGetFramework = NuGetFramework.Parse(reqFramework);
                                return _compatibilityProvider.IsCompatible(reqNuGetFramework, dgFramework);
                            });

                            if (hasMatchingFramework) {
                                supportedFrameworks[reqFramework] = versionItem.CatalogEntry.Version;
                            }
                        }
                    }

                    if (supportedFrameworks.Any()) {
                        logger?.WriteDebug($"Found matching version {versionItem.CatalogEntry.Version} for {request.PackageId} with {supportedFrameworks.Count} supported frameworks");
                        return new PackageVersionResult {
                            PackageId = request.PackageId,
                            TargetFrameworkVersions = supportedFrameworks,
                            IsPrerelease = isPrerelease
                        };
                    }
                    else if (!allowPrerelease) {
                        allowPrerelease = true;
                        goto retry;
                    }
                }
            }

            if (!allowPrerelease) {
                // some packages only have prerelease versions, try again allowing prerelease
                allowPrerelease = true;
                goto retry;
            }

            logger?.WriteDebug($"No matching version found for {request.PackageId} with any of the requested frameworks");
            return null;
        }
        catch (Exception ex) {
            logger?.WriteError($"Error fetching package metadata for {request.PackageId}", ex);
            return null;
        }
    }
}

public record CatalogRoot2 {
    [JsonPropertyName("count")]
    public int Count { get; init; }

    [JsonPropertyName("items")]
    public IReadOnlyList<CatalogPage2> Items { get; init; } = [];
}

public record CatalogPage2 {
    [JsonPropertyName("@id")]
    public string Id { get; init; } = string.Empty;
    [JsonPropertyName("@type")]
    public string Type { get; init; } = string.Empty;
    [JsonPropertyName("commitId")]
    public string CommitId { get; init; } = string.Empty;
    [JsonPropertyName("commitTimeStamp")]
    public string CommitTimeStamp { get; init; } = string.Empty;

    [JsonPropertyName("count")]
    public int Count { get; init; }

    [JsonPropertyName("items")]
    public IReadOnlyList<CatalogPageDetails2>? Items { get; set; } = default;
}


public record CatalogPageDetails2 {
    [JsonPropertyName("@id")]
    public string Id { get; init; } = string.Empty;
    [JsonPropertyName("@type")]
    public string Type { get; init; } = string.Empty;
    [JsonPropertyName("commitId")]
    public string CommitId { get; init; } = string.Empty;
    [JsonPropertyName("commitTimeStamp")]
    public string CommitTimeStamp { get; init; } = string.Empty;

    [JsonPropertyName("catalogEntry")]
    public CatalogEntry2 CatalogEntry { get; init; } = new();

    [JsonPropertyName("packageContent")]
    public string PackageContent { get; init; } = string.Empty;
    [JsonPropertyName("registration")]
    public string Registration { get; init; } = string.Empty;
}

public record CatalogEntry2 {
    [JsonPropertyName("@id")]
    public string Id { get; init; } = string.Empty;

    [JsonPropertyName("id")]
    public string PackageId { get; init; } = string.Empty;

    [JsonPropertyName("author")]
    public string Author { get; init; } = string.Empty;
    [JsonPropertyName("version")]
    public string Version { get; init; } = string.Empty;
    [JsonPropertyName("description")]
    public string description { get; init; } = string.Empty;
    [JsonPropertyName("listed")]
    public bool Listed { get; init; } = false;
    [JsonPropertyName("packageContent")]
    public string packageContent { get; init; } = string.Empty;

    [JsonPropertyName("dependencyGroups")]
    public IReadOnlyList<DependencyGroup> DependencyGroups { get; init; } = [];

    [JsonPropertyName("published")]
    public DateTimeOffset Published { get; init; }
}

public record DependencyGroup {
    [JsonPropertyName("@id")]
    public string Id { get; init; } = string.Empty;

    [JsonPropertyName("targetFramework")]
    public string TargetFramework { get; init; } = string.Empty;

    [JsonPropertyName("dependencies")]
    public IReadOnlyList<Dependency> Dependencies { get; init; } = [];
}

public record Dependency {
    [JsonPropertyName("@id")]
    public string Id { get; init; } = string.Empty;

    [JsonPropertyName("id")]
    public string PackageId { get; init; } = string.Empty;

    [JsonPropertyName("range")]
    public string Range { get; init; } = string.Empty;

    [JsonPropertyName("registration")]
    public string Registration { get; init; } = string.Empty;
}

[JsonSerializable(typeof(CatalogRoot2))]
[JsonSerializable(typeof(CatalogPage2))]
[JsonSerializable(typeof(CatalogPageDetails2))]
[JsonSerializable(typeof(CatalogEntry2))]
[JsonSerializable(typeof(DependencyGroup))]
[JsonSerializable(typeof(Dependency))]
public partial class CatalogJsonContext : JsonSerializerContext;

public record NugetMetadataOptions {
    public string BaseUrl { get; init; } = "https://api.nuget.org/v3-flatcontainer/";
    public string RegistrationBaseUrl { get; init; } = "https://api.nuget.org/v3/registration5-gz-semver2/";
    public string SearchQueryUrl { get; init; } = "https://azuresearch-usnc.nuget.org/query";
    public string PackageVersionsUrl { get; init; } = "https://api.nuget.org/v3-flatcontainer/";
    public TimeSpan CacheExpiration { get; init; } = TimeSpan.FromMinutes(30);
    public TimeSpan HttpTimeout { get; init; } = TimeSpan.FromSeconds(30);
    public int MaxParallelRequests { get; init; } = 10;
}

public record PackageVersionRequest {
    public required string PackageId { get; init; }
    public bool AllowPrerelease { get; init; }
    public bool IsPrivateAssets { get; init; } = false;
    public required IReadOnlyList<string> CompatibleTargetFrameworks { get; init; }
}


public record PackageVersionResult {
    public required string PackageId { get; init; }
    public required Dictionary<string, string> TargetFrameworkVersions { get; init; }
    public bool IsPrerelease { get; init; }
    public DateTime RetrievedAt { get; init; } = DateTime.UtcNow;
}